export const REGISTRATION: 'REGISTRATION' = 'REGISTRATION';
export const REGISTRATION_SUCCESS: 'REGISTRATION_SUCCESS' = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILED: 'REGISTRATION_FAILED' = 'REGISTRATION_FAILED';

export const LOGIN: 'LOGIN' = 'LOGIN';
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = 'LOGIN_SUCCESS';
export const LOGIN_FAILED: 'LOGIN_FAILED' = 'LOGIN_FAILED';
export const LOGIN_END: 'LOGIN_END' = 'LOGIN_END';

export const GET_USER_INFORMATION: 'GET_USER_INFORMATION' = 'GET_USER_INFORMATION';
export const GET_USER_INFORMATION_SUCCESS: 'GET_USER_INFORMATION_SUCCESS' = 'GET_USER_INFORMATION_SUCCESS';
export const GET_USER_INFORMATION_FAILED: 'GET_USER_INFORMATION_FAILED' = 'GET_USER_INFORMATION_FAILED';

export const UPDATE_TOKEN: 'UPDATE_TOKEN' = 'UPDATE_TOKEN';
export const UPDATE_TOKEN_SUCCESS: 'UPDATE_TOKEN_SUCCESS' = 'UPDATE_TOKEN_SUCCESS';
export const UPDATE_TOKEN_FAILED: 'UPDATE_TOKEN_FAILED' = 'UPDATE_TOKEN_FAILED';

export const UPDATE_USER_INFORMATION: 'UPDATE_USER_INFORMATION' = 'UPDATE_USER_INFORMATION';
export const UPDATE_USER_INFORMATION_SUCCESS: 'UPDATE_USER_INFORMATION_SUCCESS' = 'UPDATE_USER_INFORMATION_SUCCESS';
export const UPDATE_USER_INFORMATION_FAILED: 'UPDATE_USER_INFORMATION_FAILED' = 'UPDATE_USER_INFORMATION_FAILED';

export const LOGOUT: 'LOGOUT' = 'LOGOUT';
